# Site settings
title: Video about
description: > # this means to ignore newlines until "baseurl:"
  It says how those who have experienced various area and background describe Working Holiday to Australia and what it was like for them.
  They say it is a privilege for the twenties
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
