title: 길따라 멋따라
description: 2분반 3조

url: https://yunzi3.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5


social:
   github: yunzi3
   twitter: yunzi3
   facebook: yunzi3
   email: torokoko123@gmail.com

google_analytics: "UA-58263416-1"
