title: 길따라 멋따라
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://guheon.github.io/tblog/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 7

navigation:
 - title: 자전거선택
   url: /2015-05-23-자전거선택
 - title: 돌발상황
   url: /2015-05-24-돌발상황대처
 - title: 기본지식
   url: /2015-05-25-자전거지식
 - title: 주의사항
   url: /2015-05-26-주의사항 
   - title: 장비
   url: /2015-05-27-자전거장비
   - title: 계획
   url: /2015-05-28-여행계획
   - title: 자전거코스
   url: /2015-05-29-대표자전거코스
social:
   github: torokoko1
   twitter: torokoko1
   facebook: torokoko1
   email: torokoko123@gmail.com

google_analytics: "UA-58263416-1"
